name: FolConn application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Dependencies install
      run: |
        cd src
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
